# Generated by Django 4.2.16 on 2026-06-24 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=500)),
                ('public_url', models.URLField()),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('study_material', 'Study Material'), ('assignment', 'Assignment'), ('submission', 'Submission'), ('profile', 'Profile'), ('other', 'Other')], default='other', max_length=30)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.semester')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.subject')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploaded_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
