services:
  - type: web
    name: eduai-backend
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,.onrender.com,student-assistant-980q.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: eduai-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: eduai-redis
          type: redis
          property: connectionString
      - key: FRONTEND_URL
        value: "https://student-assistant-a2i8.vercel.app"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://student-assistant-a2i8.vercel.app"
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: student_assistant
      - key: YOUTUBE_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CHROMA_PERSIST_DIR
        value: /opt/render/project/src/chroma_db

  - type: redis
    name: eduai-redis
    plan: free
    ipAllowList: []

databases:
  - name: eduai-db
    databaseName: student_assistant
    plan: free
