# Generated by Django 4.2.16 on 2026-07-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_add_youtube_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
