# Generated by Django 4.2.16 on 2026-07-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_videofolder_youtube_extended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuberesource',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('watching', 'Watching'), ('completed', 'Completed')], default='saved', max_length=20),
        ),
    ]
