# Generated by Django 4.2.16 on 2026-07-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_plannertask_google_calendar_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannertask',
            name='google_calendar_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file_url',
            field=models.URLField(max_length=1000),
        ),
    ]
